context:
  version: "5.5"

package:
  name: direvent
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/direvent/direvent-${{ version }}.tar.gz
  sha256: 0e16c0b4b3e6f7673e9b4f31d81ab01236ad22f83538512f3b2f58f9f96fdcb7

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - gettext-tools
    - make
    - sed
  host:
    - libtool
    - if: not linux
      then: libintl-devel

tests:
  - script:
      - direvent --help

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Monitors events in the file system directories
  homepage: https://www.gnu.org.ua/software/direvent

extra:
  recipe-maintainers:
    - danielnachun
